Refactor code to reference "verifiable credential" as VC
idpass/inji pull request #132
Opened 2022-03-23 06:16 UTC by danicaerediano

Closes #75

2022-03-23 06:52 UTC, pmigueld requested changes
@nicholemnl please check if I missed anything. Best to have more eyes on big refactors like this.

2022-03-23 06:52 UTC, pmigueld commented on machines/settings.ts
> +    VCLabel: {
Can you change this (and other references) to `vcLabel` to distinguish from the `VCLabel` type?

2022-03-23 06:52 UTC, pmigueld commented on screens/Home/HomeScreenController.ts
> +import { selectVCLabel } from '../../machines/settings';
Let's keep it consistent with camelCase `selectVcLabel`.

2022-03-23 06:52 UTC, pmigueld commented on screens/Home/MyVcs/DownloadingVcModalController.ts
> +export function useDownloadingvcModal() {
I think this was a typo from me, please fix to `useDownloadingVcModal`.

2022-03-25 03:51 UTC, nicholemnl commented on screens/Request/RequestScreenController.ts
> +    statusMessage = `Connected to device. Waiting for ${VCLabel.singular}...`;
Shouldn't this be small vcLabel?

2022-03-28 05:17 UTC, nicholemnl approved these changes

2022-03-30 05:53 UTC, pmigueld approved these changes

2022-04-04 01:23 UTC, merged